webtalk_init -webtalk_dir C:/Users/Mark1/Downloads/BPC-DE1/DE1 projekt/Slvik cycle+count_1sec/projekt-DE1-2021/Slavik cycle+count_1sec/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_count_1sec_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 20 22:28:45 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c8cbb0c6-07a9-40ee-a04b-f31cdd5a7691" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4256a919eaf74c68aab800fb57ccd8d6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6252_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3330624623 -regid "" -xml C:/Users/Mark1/Downloads/BPC-DE1/DE1 projekt/Slvik cycle+count_1sec/projekt-DE1-2021/Slavik cycle+count_1sec/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_count_1sec_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Mark1/Downloads/BPC-DE1/DE1 projekt/Slvik cycle+count_1sec/projekt-DE1-2021/Slavik cycle+count_1sec/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_count_1sec_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Mark1/Downloads/BPC-DE1/DE1 projekt/Slvik cycle+count_1sec/projekt-DE1-2021/Slavik cycle+count_1sec/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_count_1sec_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
